-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 19:32:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wmsdb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wmsdb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wmsdb2` DEFAULT CHARACTER SET utf8 ;
USE `wmsdb2` ;

-- -----------------------------------------------------
-- Table `wmsdb2`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`warehouse` (
  `wh_id` INT NOT NULL AUTO_INCREMENT COMMENT '自增',
  `wh_name` VARCHAR(45) NOT NULL COMMENT '仓库名 非空 唯一',
  `wh_type` VARCHAR(45) NULL DEFAULT 'default type' COMMENT '仓库类型 默认 default type',
  `num_shelf` INT NULL DEFAULT 0 COMMENT '可容纳货架数量 默认0',
  `num_good` INT NULL DEFAULT 0 COMMENT '当前货物数量 默认0',
  `creat_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '仓库创建时间 自动获取系统当前时间',
  PRIMARY KEY (`wh_id`),
  UNIQUE INDEX `wh_name_UNIQUE` (`wh_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户 ID 主键 自增',
  `username` VARCHAR(45) NOT NULL COMMENT '用户名 非空 唯一 用于登录',
  `staff_password` VARCHAR(45) NOT NULL COMMENT '用户密码',
  `name` VARCHAR(45) NOT NULL COMMENT '用户姓名 非空',
  `age` INT NULL COMMENT '年龄',
  `gender` VARCHAR(45) NULL COMMENT '性别',
  `phone` VARCHAR(45) NULL COMMENT '电话',
  `is_manager` TINYINT NOT NULL DEFAULT 0 COMMENT '身份：管理者1 工人0 非空 默认0',
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`staff_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`staff_access` (
  `staff_staff_id` INT NOT NULL,
  `warehouse_wh_id` INT NOT NULL,
  PRIMARY KEY (`staff_staff_id`, `warehouse_wh_id`),
  INDEX `fk_staff_has_warehouse_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  INDEX `fk_staff_has_warehouse_staff_idx` (`staff_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_has_warehouse_staff`
    FOREIGN KEY (`staff_staff_id`)
    REFERENCES `wmsdb2`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_has_warehouse_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb2`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`shelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`shelf` (
  `shelf_id` INT NOT NULL AUTO_INCREMENT,
  `shelf_name` VARCHAR(45) NULL COMMENT '货架名',
  `num_floor` INT NOT NULL DEFAULT 5 COMMENT '货架层数 非空 默认5',
  `warehouse_wh_id` INT NOT NULL COMMENT '货架所在仓库 ID',
  PRIMARY KEY (`shelf_id`, `warehouse_wh_id`),
  INDEX `fk_shelf_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_shelf_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb2`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`good`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`good` (
  `good_id` INT NOT NULL AUTO_INCREMENT COMMENT '自增',
  `good_name` VARCHAR(45) NOT NULL COMMENT '货物名 非空',
  `good_type` VARCHAR(45) NOT NULL DEFAULT 'default type' COMMENT '货物类型 非空',
  `floor` INT NOT NULL DEFAULT 1 COMMENT '所在货架层数 非空',
  `warehousing_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间 非空 自动获取系统当前时间',
  `shelf_shelf_id` INT NOT NULL COMMENT '所在货架 ID',
  `shelf_warehouse_wh_id` INT NOT NULL COMMENT '所在仓库 ID',
  PRIMARY KEY (`good_id`, `shelf_shelf_id`, `shelf_warehouse_wh_id`),
  INDEX `fk_good_shelf1_idx` (`shelf_shelf_id` ASC, `shelf_warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_good_shelf1`
    FOREIGN KEY (`shelf_shelf_id` , `shelf_warehouse_wh_id`)
    REFERENCES `wmsdb2`.`shelf` (`shelf_id` , `warehouse_wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`robot` (
  `robot_id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_wh_id` INT NOT NULL,
  PRIMARY KEY (`robot_id`, `warehouse_wh_id`),
  INDEX `fk_robot_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_robot_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb2`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb2`.`log_robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb2`.`log_robot` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `send_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `host_ip` VARCHAR(45) NULL,
  `file_size` DECIMAL(10,3) NULL,
  `rec_status` TINYINT NULL,
  `write_status` TINYINT NULL,
  `robot_robot_id` INT NOT NULL,
  `robot_warehouse_wh_id` INT NOT NULL,
  PRIMARY KEY (`log_id`, `robot_robot_id`, `robot_warehouse_wh_id`),
  INDEX `fk_log_robot_robot1_idx` (`robot_robot_id` ASC, `robot_warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_robot_robot1`
    FOREIGN KEY (`robot_robot_id` , `robot_warehouse_wh_id`)
    REFERENCES `wmsdb2`.`robot` (`robot_id` , `warehouse_wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
