-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 23:01:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wmsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wmsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wmsdb` DEFAULT CHARACTER SET utf8 ;
USE `wmsdb` ;

-- -----------------------------------------------------
-- Table `wmsdb`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`warehouse` (
  `wh_id` INT NOT NULL AUTO_INCREMENT COMMENT 'warehouse id, unique and auto increment',
  `wh_name` VARCHAR(45) NOT NULL COMMENT 'warehouse name, unique and not null',
  `wh_type` VARCHAR(45) NULL DEFAULT 'default type' COMMENT 'warehouse type, defaults: default type',
  `num_shelf` INT NULL DEFAULT 0 COMMENT 'number of shelves, defaults: 0',
  `num_good` INT NULL DEFAULT 0 COMMENT 'quantity of goods, defaults:0',
  `creat_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'warehouse creation time, automatically obtain the current time of the system',
  PRIMARY KEY (`wh_id`),
  UNIQUE INDEX `wh_name_UNIQUE` (`wh_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT COMMENT 'user id, auto increment',
  `username` VARCHAR(45) NOT NULL COMMENT 'username, unique and not null, for login',
  `staff_password` VARCHAR(45) NOT NULL COMMENT 'user password, not null',
  `name` VARCHAR(45) NOT NULL COMMENT 'real name, not null',
  `age` INT NULL COMMENT 'defaults: null',
  `gender` VARCHAR(45) NULL COMMENT 'defaults: null',
  `phone` VARCHAR(45) NULL COMMENT 'defaults: null',
  `is_manager` TINYINT NOT NULL DEFAULT 0 COMMENT 'manager:1, worker:0, not null, defaults: 0',
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`staff_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`staff_access` (
  `staff_staff_id` INT NOT NULL COMMENT 'user id, foreign key',
  `warehouse_wh_id` INT NOT NULL COMMENT 'warehouse id, foreign key',
  PRIMARY KEY (`staff_staff_id`, `warehouse_wh_id`),
  INDEX `fk_staff_has_warehouse_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  INDEX `fk_staff_has_warehouse_staff_idx` (`staff_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_has_warehouse_staff`
    FOREIGN KEY (`staff_staff_id`)
    REFERENCES `wmsdb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_has_warehouse_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`shelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`shelf` (
  `shelf_id` INT NOT NULL AUTO_INCREMENT COMMENT 'shelf id, auto increment',
  `shelf_name` VARCHAR(45) NULL COMMENT 'shelf name, defaults: null',
  `num_floor` INT NOT NULL DEFAULT 5 COMMENT 'max layer number of the shelf, not null, defaults: 5',
  `warehouse_wh_id` INT NOT NULL COMMENT 'warehouse where the shelf is located, foreign key',
  PRIMARY KEY (`shelf_id`, `warehouse_wh_id`),
  INDEX `fk_shelf_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_shelf_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`good`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`good` (
  `good_id` INT NOT NULL AUTO_INCREMENT COMMENT 'good id, auto increment',
  `good_name` VARCHAR(45) NOT NULL COMMENT 'good name, not null',
  `good_type` VARCHAR(45) NOT NULL DEFAULT 'default type' COMMENT 'good type, notnull, defaults: default type',
  `floor` INT NOT NULL DEFAULT 1 COMMENT 'floor number of the shelf where the good is located, not null, defaults: 1',
  `warehousing_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'warehousing time, not null, automatically obtain the current time of the system',
  `shelf_shelf_id` INT NOT NULL DEFAULT 0 COMMENT 'shelf id where the good is located, not null, defaults: 0',
  `shelf_warehouse_wh_id` INT NOT NULL DEFAULT 0 COMMENT 'warehouse id where the good is located, not null, defaults: 0',
  PRIMARY KEY (`good_id`, `shelf_shelf_id`, `shelf_warehouse_wh_id`),
  INDEX `fk_good_shelf1_idx` (`shelf_shelf_id` ASC, `shelf_warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_good_shelf1`
    FOREIGN KEY (`shelf_shelf_id` , `shelf_warehouse_wh_id`)
    REFERENCES `wmsdb`.`shelf` (`shelf_id` , `warehouse_wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`robot` (
  `robot_id` INT NOT NULL AUTO_INCREMENT COMMENT 'robot id, not null and auto increment',
  `warehouse_wh_id` INT NOT NULL COMMENT 'warehouse id where the robot works, foreign key',
  PRIMARY KEY (`robot_id`, `warehouse_wh_id`),
  INDEX `fk_robot_warehouse1_idx` (`warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_robot_warehouse1`
    FOREIGN KEY (`warehouse_wh_id`)
    REFERENCES `wmsdb`.`warehouse` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wmsdb`.`log_robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wmsdb`.`log_robot` (
  `log_id` INT NOT NULL AUTO_INCREMENT COMMENT 'log id, not null and auto increment',
  `send_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'send time, not null, automatically obtain the current time of the system',
  `host_ip` VARCHAR(45) NULL COMMENT 'host ip, defaults: null',
  `file_size` DECIMAL(10,3) NULL COMMENT 'file size, defaults: null',
  `rec_status` TINYINT NULL COMMENT 'receive status, defaults: null',
  `write_status` TINYINT NULL COMMENT 'write status, defaults: null',
  `robot_robot_id` INT NOT NULL COMMENT 'robot who wrote this log, not null, foreign key',
  `robot_warehouse_wh_id` INT NOT NULL COMMENT 'warehouse where the robot works, not null, foreign key',
  PRIMARY KEY (`log_id`, `robot_robot_id`, `robot_warehouse_wh_id`),
  INDEX `fk_log_robot_robot1_idx` (`robot_robot_id` ASC, `robot_warehouse_wh_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_robot_robot1`
    FOREIGN KEY (`robot_robot_id` , `robot_warehouse_wh_id`)
    REFERENCES `wmsdb`.`robot` (`robot_id` , `warehouse_wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
